export default {
    ON_BOARDING: 'onBoarding',
    INITIAL_AUTH: "initialAuth",
    LOGIN: "login",
    SIGNUP: "signup",
    OTP_VERIFICATION: "otpVerification",
    FORGOT_PASSWORD: "forgotPassword",
    HOME:"home",
    SEARCH:"Search",
    POST:"Post",
    NOTIFICATION:"Notification",
    PROFILE:"Profile",
    CATEGORIES:"categories",
    BOOK_SELECTIONS:"bookSelections",
    ANIMATION:"animation",
}
